apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danswer-stack.fullname" . }}-indexing-model
  labels:
    {{- range .Values.indexCapability.deployment.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  replicas: {{ .Values.indexCapability.deployment.replicas }}
  selector:
    matchLabels:
      {{- range .Values.indexCapability.deployment.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.indexCapability.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- range .Values.indexCapability.podLabels }}
        {{ .key }}: {{ .value }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.indexCapability.name }}
        image: {{ .Values.indexCapability.deployment.image.repository }}:{{ .Values.indexCapability.deployment.image.tag }}
        imagePullPolicy: {{ .Values.indexCapability.deployment.image.pullPolicy }}
        command: {{ toYaml .Values.indexCapability.deployment.command | nindent 14 }}
        ports:
        - containerPort: {{ .Values.indexCapability.service.port }}
        envFrom:
          - configMapRef:
              name: {{ .Values.config.envConfigMapName }}
        env:
          - name: INDEXING_ONLY
            value: "{{ default "True" .Values.indexCapability.indexingOnly }}"
          {{- include "danswer-stack.envSecrets" . | nindent 10}}
        volumeMounts:
        {{- range .Values.indexCapability.deployment.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      {{- range .Values.indexCapability.deployment.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName }}
      {{- end }}
