apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danswer-stack.fullname" . }}-inference-model
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.inferenceCapability.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "danswer-stack.selectorLabels" . | nindent 6 }}
      {{- if .Values.inferenceCapability.deployment.labels }}
      {{- toYaml .Values.inferenceCapability.deployment.labels | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "danswer-stack.labels" . | nindent 8 }}
        {{- with .Values.inferenceCapability.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.inferenceCapability.name }}
        image: {{ .Values.inferenceCapability.deployment.image.repository }}:{{ .Values.inferenceCapability.deployment.image.tag }}
        imagePullPolicy: {{ .Values.inferenceCapability.deployment.image.pullPolicy }}
        command: {{ toYaml .Values.inferenceCapability.deployment.command | nindent 14 }}
        ports:
        - containerPort: {{ .Values.inferenceCapability.service.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.config.envConfigMapName }}
        env:
          {{- include "danswer-stack.envSecrets" . | nindent 12}}
        volumeMounts:
        {{- range .Values.inferenceCapability.deployment.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      {{- range .Values.inferenceCapability.deployment.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName }}
      {{- end }}
