name: Python Unit Tests

on:
  merge_group:
  pull_request:
    branches: [ main ]

jobs:
  check-changes:
    uses: ./.github/workflows/check-backend-changes.yml

  backend-check:
    needs: check-changes
    if: needs.check-changes.outputs.run-tests == 'true'
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ./backend
      REDIS_CLOUD_PYTEST_PASSWORD: ${{ secrets.REDIS_CLOUD_PYTEST_PASSWORD }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          backend/requirements/default.txt
          backend/requirements/dev.txt

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements/default.txt
        pip install -r backend/requirements/dev.txt

    - name: Run Tests
      shell: script -q -e -c "bash --noprofile --norc -eo pipefail {0}"
      run: py.test -o junit_family=xunit2 -xv --ff backend/tests/unit


  skip-tests:
    needs: check-changes
    if: needs.check-changes.outputs.run-tests == 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes in backend, skipping this test."
